### ISSUE TITLE
Samsung Galaxy Tab S4 not recognized

### ISSUE THREAD

**Issue by wolli1234** [Samsung-Loki/Hreidmar#6]
Hello,

I'm looking for an alternative to [heimdall 2.0.1](https://git.sr.ht/~grimler/Heimdall) which did not work for me flashing my Samsung Galaxy Tab S4. I can run Hreidmar.GUI but my device is not detected correctly.

Only thing that shows up under devices is "Samsung - MSM8998", which seems to be Galaxy S8 (which would be wrong). 

Trying to connect anyway and then there comes an unable to write error. Unfortunately I can't copy paste the text out of the log file, and I don't know where it is saved.
Would be great to see an alternative to Heimdall coming up for linux! If you can tell me how to save the log of course I would like to post it here.

Best regards,
Wolli

**Comment by TheAirBlow** [comment]
Hello,

Most of snapdragon phones are locked and are unflasheable (As MSM8998 says)
Also, you can screenshot the logs instead of copy-paste.

**Comment by wolli1234** [comment]
Hello,

System:    Kernel: 5.10.0-11-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.10.0-11-amd64 
           root=UUID=<filter> ro quiet splash 
           Desktop: Xfce 4.16.0 tk: Gtk 3.24.24 info: xfce4-panel wm: xfwm 4.16.1 vt: 7 
           dm: LightDM 1.26.0 Distro: MX-21_x64 Wildflower October 20  2021 
           base: Debian GNU/Linux 11 (bullseye)

More background info: I can sucessfully download PIT through heimdall. I tried flashing with odin3 in virtualbox, which gives a success message, but does not really flash. The Galaxy Tab S4 is in a constant boot loop with black screen. Can't restart or turn it on or off anymore, buttons are not working. Only way to get it into download mode is waiting until the battery is totally empty when it was in boot loop state. Then the buttons are working again and I can put it into download mode.

I did not know about snapdragon phone problems with flashing, that would be bad news, but thank you for the info.

And here are screenshots of the logs. I tried version 3 and version 4 with the same results.
![v4_1](https://user-images.githubusercontent.com/23383106/156880987-fc034407-13e5-4849-95ff-abb174db9330.png)
![v4_2](https://user-images.githubusercontent.com/23383106/156880994-0da0cb41-61b9-4c60-8530-2a64b866f3f7.png)

**Comment by wolli1234** [comment]
> MSM8998

**Comment by wolli1234** [comment]
> Most of snapdragon phones are locked and are unflasheable (As MSM8998 says)

My Galaxy Tab S4 is the wifi only version (T830), I suppose this is unlocked in general?

**Comment by TheAirBlow** [comment]
If Heimdall didn't work, neither would Hreidmar:
1) It is in development (and not active as you can see)
2) 90% of the protocol is copied from Heimdall

P.S. It cannot even connect, I would make debugging easier in new implementation

**Comment by TheAirBlow** [comment]
@wolli1234, If it cannot even connect, it is probably cause your bootloader is very corrupted.
Not working buttons is 100% fucked up BL. Better take your tablet to a service center.

It errors out while trying to get descriptors - which is very, very, VERY bad.
If you can send me proof of Heimdall connecting, and Heimdall (the old version that you have, right now even connecting is To-Do) erroring out, please respond, the issue would be reopened.

**Comment by TheAirBlow** [comment]
Actually, it can be a sign that you didn't run Thor as admin. The error is the same.

**Comment by wolli1234** [comment]
Thanks for your reply, I managed to flash it with odin in the end: [xda-forum](https://forum.xda-developers.com/t/galaxy-tab-s4-sm-t830-blocked-in-bootloop.4349853/post-86634059)

It was not the bootloader, but I think there is a hardware issue with the battery, as in the meanwhile the tab is dead again...
